name: Update and Combine Rule Files from Remote Repos blackmatrix7

on:
  schedule:
    - cron: '0 4 * * *'  # 每天凌晨4点检查一次更新
  workflow_dispatch:  # 手动触发

jobs:
  update-and-combine-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # 创建 QuantumultX 目录并切换到该目录
      - name: Create QuantumultX Directory
        run: mkdir -p QuantumultX 


      # 下载文件Netflix (直接引用)
      - name: Download Netflix.list
        run: curl -o QuantumultX/Netflix.list https://raw.githubusercontent.com/moshall/ios_rule_script/master/rule/QuantumultX/Netflix/Netflix.list

      # 下载文件BardAI、OpenAI、Claude 并合并
      - name: Download and Combine BardAI.list, OpenAI.list, and Claude.list
        run: |
          curl -o QuantumultX/BardAI.list https://raw.githubusercontent.com/moshall/ios_rule_script/master/rule/QuantumultX/BardAI/BardAI.list
          curl -o QuantumultX/OpenAI.list https://raw.githubusercontent.com/moshall/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list
          curl -o QuantumultX/Claude.list https://raw.githubusercontent.com/moshall/ios_rule_script/master/rule/QuantumultX/Claude/Claude.list
          cat QuantumultX/BardAI.list QuantumultX/OpenAI.list QuantumultX/Claude.list > QuantumultX/AI_Combined.list
          rm QuantumultX/BardAI.list QuantumultX/OpenAI.list QuantumultX/Claude.list  # 删除不需要的文件


      # 下载文件XPTV.list (直接引用)
      - name: Download XPTV.list
        run: curl -o QuantumultX/XPTV.list https://raw.githubusercontent.com/fangkuia/XPTV/main/X/QuantumultX.list


      # 下载文件YouTube.list (直接引用)
      - name: Download YouTube.list
        run: curl -o QuantumultX/YouTube.list https://raw.githubusercontent.com/moshall/ios_rule_script/master/rule/QuantumultX/YouTube/YouTube.list

      # 提交并推送合并后的文件
      - name: Commit and Push Combined Files
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add QuantumultX/Netflix.list QuantumultX/AI_Combined.list QuantumultX/YouTube.list QuantumultX/XPTV.list
          git diff-index --quiet HEAD || git commit -m "Update and combine files from remote repositories"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/moshall/mk_rule.git
          git push origin HEAD:main
